name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set AWS credentials
        uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          access_key_id: ${{ secrets.PROG_AWS_ACCESS_KEY }}
          secret_access_key: ${{ secrets.PROG_AWS_SECRET }}
          region: ${{ env.AWS_REGION }}

      - run: chmod +x gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - run: ./gradlew test
